apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traccar
  namespace: flux-system
spec:
  interval: 10m
  releaseName: traccar
  targetNamespace: traccar
  chart:
    spec:
      chart: traccar
      sourceRef:
        kind: HelmRepository
        name: traccar
        namespace: flux-system
      interval: 10m
  install:
    createNamespace: true
    remediation:
      retries: 3