apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: monicahq
  namespace: flux-system
spec:
  interval: 10m
  releaseName: monicahq
  targetNamespace: monicahq
  chart:
    spec:
      chart: charts/monica
      sourceRef:
        kind: GitRepository
        name: monicahq
        namespace: flux-system
      interval: 10m
  install:
    createNamespace: true
    remediation:
      retries: 3