apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: oauth2-proxy
  namespace: flux-system
spec:
  interval: 10m
  releaseName: oauth2-proxy
  targetNamespace: oauth2-proxy
  chart:
    spec:
      chart: oauth2-proxy
      version: "7.6.0"
      sourceRef:
        kind: HelmRepository
        name: oauth2-proxy
        namespace: flux-system
      interval: 10m
  install:
    createNamespace: true
    remediation:
      retries: 3