---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: nginx-ingress
  namespace: flux-system
  labels:
    org.zroot.gitops: infra
spec:
  interval: 5m
  url: https://helm.nginx.com/stable