repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1  # Use the ref you want to point at
    hooks:
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-symlinks
      - id: detect-private-key
      - id: check-yaml
        args: ["-m"]
  # - repo: https://github.com/ansible/ansible-lint/
  #   rev: v6.15.0
  #   hooks:
  #     - id: ansible-lint
  #       args: ["-v"]
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.50.0
    hooks:
      - id: terraform_fmt
      - id: terraform_validate
      - id: terraform_docs_replace
  - repo: https://github.com/cisagov/pre-commit-packer
    rev: v0.0.2
    hooks:
      # - id: packer_fmt
      - id: packer_validate
