apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
    name: acme-digitalocean
    namespace: cert-manager
spec:
    acme:
        email: acme@mbovo.me
        server: https://acme-v02.api.letsencrypt.org/directory
        solvers:
            - dns01:
                digitalocean:
                    tokenSecretRef:
                        name: digitalocean-dns
                        key: access-token
---
apiVersion: v1
kind: Secret
metadata:
    name: digitalocean-dns
    namespace: cert-manager
data:
    access-token: YmFzZTY0IGVuY29kZWQgYWNjZXNzLXRva2VuIGhlcmU=
