apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cert-manager
  namespace: flux-system
  labels:
    org.zroot.gitops: infra
spec:
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./high/infra/certmanager
  prune: true
  dependsOn:
    - name: metallb
      namespace: flux-system