apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: oauth2-proxy
  namespace: flux-system
spec:
  valuesFrom:
    - kind: ConfigMap
      name: oauth2-values
    - kind: Secret
      name: oauth2-secrets