apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../apps/oauth2-proxy/
- ./traefikmiddleware.yaml
patches:
- path: helmrelease.yaml
configMapGenerator:
- files:
  - values.yaml=values.yaml
  name: oauth2-values
  namespace: flux-system
secretGenerator:
- files:
  - values.yaml=secrets.yaml
  name: oauth2-secrets
  namespace: flux-system
configurations:
- kustomizeconfig.yaml
