apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: oauth2-forwardauth
  namespace: oauth2-proxy
spec:
  forwardAuth:
    address: 'https://auth.k.zroot.org/oauth2/'
    trustForwardHeader: true
    authResponseHeaders:
      - X-Auth-Request-Access-Token
      - Authorization
