---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metrics-server
  namespace: flux-system
  labels:
    org.zroot.gitops: infra
spec:
  interval: 10m
  releaseName: metrics-server
  targetNamespace: kube-system
  upgrade:
    crds: CreateReplace
  install:
    createNamespace: true
    crds: CreateReplace
  chart:
    spec:
      chart: metrics-server
      version: '>=3.8.2 <4.0.0'
      sourceRef:
        kind: HelmRepository
        name: kube-sigs-metric-server
        namespace: flux-system
      interval: 10m
  values:
    apiService:
      create: true
    metrics:
      enabled: true
    serviceMonitor:
      enabled: false