apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
    name: acme-digitalocean
    namespace: cert-manager
spec:
    acme:
        privateKeySecretRef:
            name: acme-digitalocean-key
        email: ENC[AES256_GCM,data:IQtNtst/iHPlY9Uhfg==,iv:5cxKpeoS7JUhlofCwAe2WSxQ4lftfNwvXEFN+waQdoc=,tag:ygy6V5od2FOeY7TOpD9DKA==,type:str]
        server: ENC[AES256_GCM,data:+TJMDJwfgCqIGkewtX562Ra4NIAPSwxDmnYWxuW1l4n2j4f8tBe+ClTVXersuQ==,iv:0n6IkdqR6n7xc/DbhKHTtvNeI2W6DQ1QFuuXrO0F8XE=,tag:sRV09Y0duJvhruedHlAvkw==,type:str]
        solvers:
            - dns01:
                digitalocean:
                    tokenSecretRef:
                        name: digitalocean-dns
                        key: access-token
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-05-26T12:38:11Z"
    mac: ENC[AES256_GCM,data:EQPqpXKbKRplafEcpjmhGg74f+DASl0cmmW91o7bkD3/iWv7K3+03cncLAjrkoqyIolerrM49KKNOwutufmoz31zrAaW0tP7w2sPBm1jTiybbHAYClSATMac+PE9HeFR8hpBTYeKAT5FJ4OvutNLkaP2R2cr7gjMEmZYhlPIKQo=,iv:3OlX9Px+2J1chqkY0qtJHaG3w8fj16u18iVa5XHWv7c=,tag:3WM/QwrHNqlD6RkmQWWIpA==,type:str]
    pgp:
        - created_at: "2023-05-26T12:38:11Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA3bGu4MnJmFfAQ//XwAb2IjkGCwp7ITHF2dtQc1Ln3sOIp6g76HQw7UQP8BJ
            d3Wjidq8qW0q7QhlZl/PdWLuiNBj2omFXg/i2k5r4FeC8caXLXEtTxdC4sopfD7g
            nJEF6rzd8e5cUISkzMAVJNzTsT91lcar3s+lvEKQMrICOh4I4hbWB+sRgEBS3A+G
            E8AbNiup6/GIdn6EYTrLLpTLe8zcbGQNqyso6PdJ/sdA5T6E+FKB2psUTkzqwv5b
            AqYhAXlZQhnh+eNTSyVCGZGwtccOZJb+q/dSVo/KyDulwsI4dvCStyFxQG5qy8hx
            ddg7LG8THOnG3AeupVIbCP5i1wdU76Ft4qSaXnb4IQRlh5VXCSO6hsEaH33d8p8S
            bCsvKzqKSfETCYuMEf16/Edeyt4O+UlAv/s4d/UaZYWytxf25JuHiW1qQH3fzoz6
            4rIvy50nSXQT6Tqn2o4a0p/K97VVQ9YEGcrDx3pJDV3IyQ5fV4H6q3SXGhQuLA3v
            1T6GsgFm3FjZUFUnabb+Y+vLJycHOVxCs+90LYn9SMxzzRpPYILpgfVecL5FPivD
            GY3Z+jTQgH1HI1zS8TvD09Z5ajAp3XikQRl+kKL8tr3XIjgDe40WT290qM4fi73Z
            gR729X2kS68BNXoxnyoPufGuSKyEhujN+epYPB+UfFmRBC6nTi73IE0S4uJFTXvS
            XgEnpNaNN8Jl0rkCB/KHSCaq7IgeCiD0PPPnb3hIPqzGVZ4DATkwK4HrMRa7hP3A
            /zhZvyq27S0yLoZttpUN8ZMK3Jqy8g6A0ZQ9tXWhxwg6W6bQdXcwjjhtT6ppvNU=
            =GN1B
            -----END PGP MESSAGE-----
          fp: 171CF9C1D45CB28C5ECA2964FCC4AEC805651FBB
    encrypted_regex: ^(data|stringData|consumerKey|email|groupName|applicationKey|host|hosts|addresses|server|configLogicalBackup|channel)$
    version: 3.7.3
---
apiVersion: v1
kind: Secret
metadata:
    name: digitalocean-dns
    namespace: cert-manager
data:
    access-token: ENC[AES256_GCM,data:K9erXUX5riNzNhFLNsuBd4fozdB8xkT8Oj5iB/b7LaXolM3lPwjO3PvXiGNzLX7EO1Vlpxn4zBn33HRhvqFHCzk0fq+/NjvJS/kqrtKzFbiXDO34zxl258GLXoFGWh+Y,iv:mrr5HGdh60ezL3pOBoDhrAOxh2sNgj20j45NxKOIVDw=,tag:AuPzyIv3pM0UQudyOiPM6w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-05-26T12:38:11Z"
    mac: ENC[AES256_GCM,data:EQPqpXKbKRplafEcpjmhGg74f+DASl0cmmW91o7bkD3/iWv7K3+03cncLAjrkoqyIolerrM49KKNOwutufmoz31zrAaW0tP7w2sPBm1jTiybbHAYClSATMac+PE9HeFR8hpBTYeKAT5FJ4OvutNLkaP2R2cr7gjMEmZYhlPIKQo=,iv:3OlX9Px+2J1chqkY0qtJHaG3w8fj16u18iVa5XHWv7c=,tag:3WM/QwrHNqlD6RkmQWWIpA==,type:str]
    pgp:
        - created_at: "2023-05-26T12:38:11Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA3bGu4MnJmFfAQ//XwAb2IjkGCwp7ITHF2dtQc1Ln3sOIp6g76HQw7UQP8BJ
            d3Wjidq8qW0q7QhlZl/PdWLuiNBj2omFXg/i2k5r4FeC8caXLXEtTxdC4sopfD7g
            nJEF6rzd8e5cUISkzMAVJNzTsT91lcar3s+lvEKQMrICOh4I4hbWB+sRgEBS3A+G
            E8AbNiup6/GIdn6EYTrLLpTLe8zcbGQNqyso6PdJ/sdA5T6E+FKB2psUTkzqwv5b
            AqYhAXlZQhnh+eNTSyVCGZGwtccOZJb+q/dSVo/KyDulwsI4dvCStyFxQG5qy8hx
            ddg7LG8THOnG3AeupVIbCP5i1wdU76Ft4qSaXnb4IQRlh5VXCSO6hsEaH33d8p8S
            bCsvKzqKSfETCYuMEf16/Edeyt4O+UlAv/s4d/UaZYWytxf25JuHiW1qQH3fzoz6
            4rIvy50nSXQT6Tqn2o4a0p/K97VVQ9YEGcrDx3pJDV3IyQ5fV4H6q3SXGhQuLA3v
            1T6GsgFm3FjZUFUnabb+Y+vLJycHOVxCs+90LYn9SMxzzRpPYILpgfVecL5FPivD
            GY3Z+jTQgH1HI1zS8TvD09Z5ajAp3XikQRl+kKL8tr3XIjgDe40WT290qM4fi73Z
            gR729X2kS68BNXoxnyoPufGuSKyEhujN+epYPB+UfFmRBC6nTi73IE0S4uJFTXvS
            XgEnpNaNN8Jl0rkCB/KHSCaq7IgeCiD0PPPnb3hIPqzGVZ4DATkwK4HrMRa7hP3A
            /zhZvyq27S0yLoZttpUN8ZMK3Jqy8g6A0ZQ9tXWhxwg6W6bQdXcwjjhtT6ppvNU=
            =GN1B
            -----END PGP MESSAGE-----
          fp: 171CF9C1D45CB28C5ECA2964FCC4AEC805651FBB
    encrypted_regex: ^(data|stringData|consumerKey|email|groupName|applicationKey|host|hosts|addresses|server|configLogicalBackup|channel)$
    version: 3.7.3
