apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
    name: nfs-sc
    namespace: flux-system
spec:
    interval: 10m
    releaseName: nfs-sc
    targetNamespace: kube-system
    chart:
        spec:
            chart: nfs-subdir-external-provisioner
            sourceRef:
                kind: HelmRepository
                name: kubernetes-sigs-nfs
                namespace: flux-system
            interval: 10m
    values:
        nfs:
            path: /DATA/k8s
            server: ENC[AES256_GCM,data:a4fUYea68iaiQOg=,iv:PcBTAl7CdJPHrl7opxsuvbaMvrGBbC75QQsBBdG1y40=,tag:HnMxN557ORaEVhNaV2LjsQ==,type:str]
        storageClass:
            defaultClass: true
            name: nfs-sc
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-05-26T10:01:04Z"
    mac: ENC[AES256_GCM,data:JYEbIosh/FdkCjfhh4PWItlMcCsp91T70Wbqkemrbr6S0g1AtxoXflzxQKiSAyCFWsrqXmtzKAY2HOKkIeTInM3DdOJhtnAdFNXBsGCglzmHCR2A13fV7qFkjqOAmImsH14gCwlfP6i5it/og8D0eziSC28Z6NJJDIYFfDnPuDI=,iv:4rNSlDVIplcpBmPUgegHZJWjc9F74Wt9PyDbyoXJblE=,tag:8efvKNgAxsD96olI+Uruhg==,type:str]
    pgp:
        - created_at: "2023-05-26T10:01:03Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA3bGu4MnJmFfARAAhoP0h80w/C7AlVHiRYstny2/CX4s+bDbR+vnviSd48vu
            nZQ54wohxelIPdcdiWXvB/D5u4yL4655mWnqfijbtuXu1SXNfjzNUdqY+5wDELpV
            wxn+UmXApBcWuQhGvSlpAD5aS4Li/FlaQf/14BpNcVXhSwo7flM+XADZ7sMw3/gv
            nwNr3woctFq5l36a5lno7OpPgTAoQLZiRnfhxwPxGt2PLgKJGmrQZnz1nttwjP7M
            uNtHp7RwbNUThD4C4+wRWScQosvf7Pt49EPdoD1N456Fr1fzTnFp3cBU9JJC4uNi
            lYSF7aP9E/vsVTUKKsN8xfV7XOfp/1kBXJocAW88rTouACFDrEJFndWt7BtMFwZ0
            zjnImXg0hS4tIYXrU5tiL+vu5nVMtUBIW4N8rP1JGIuXTGw/UUepe6ddCM0rUbmD
            Ulmx8d+I37t3pjEz5Cf2vpwic3Wli4chaaBDmhkDYOq9iB99J/2hxPYEUW4lzqVE
            +VLuEOniXohZaGfHxQoJb3iHG27dk5ZSD0vZla5SETh+o0XaB4TYP7Clfew8APmw
            UBLYNQ4tREnFfVanjjymRKoNfF7zHq3cPvrG4Ikdz5OvXdDaohlR5yPQ8JoaSYUL
            iS+TY91O20I3gzdp+TztVPCy1CS/etTH2S9/30vV5BMZnOEWcnso00dQYiT+8CHS
            WwE3yfaotZ/bNAaZ46qAdVNVpjJXEZO0AHJu65REmUr7Fn3QrL3hRfiX+OLIq2aN
            rIdbl6NpeLcgH+G52oD30Y/vaurGyKvpgib9bwS+l30hbZ51ThM6J5w/NFY=
            =RTJF
            -----END PGP MESSAGE-----
          fp: 171CF9C1D45CB28C5ECA2964FCC4AEC805651FBB
    encrypted_regex: ^(data|stringData|consumerKey|email|groupName|applicationKey|host|hosts|addresses|server|configLogicalBackup|channel)$
    version: 3.7.3
