apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
    name: nfs-sc
    namespace: flux-system
spec:
    interval: 10m
    releaseName: nfs-sc
    targetNamespace: kube-system
    chart:
        spec:
            chart: nfs-subdir-external-provisioner
            sourceRef:
                kind: HelmRepository
                name: kubernetes-sigs-nfs
                namespace: flux-system
            interval: 10m
    values:
        nfs:
            path: /DATA
            server: ENC[AES256_GCM,data:GikNfjwME/nl8Oo=,iv:lPWqy3J6LbNRgW9Bve7Hx6qAuGwQUzXLMSEMXuMwLSM=,tag:A4vE24FdHQiHhLr6K2oDYw==,type:str]
        storageClass:
            defaultClass: true
            name: nfs-sc
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-05-26T08:50:47Z"
    mac: ENC[AES256_GCM,data:zt72HPgSRUJYTReZ1T0hhUQZjRAg0W7tZU5T1aYj7yupGxRHA3Bpg/Msu016x8KkVINgWQxkVn3fS6lK7h/D67lhQvqP2vvcnmQO3rp/Zc9RF+CVjmb3sqKPVvDWaP1n0mCsXDSS0PHNTvzKe9lsAUU4yU7g1CncTgHZ1rNgFak=,iv:KZZ49ABFn0hEOysqUwuEV2idVwq9vAMJi9MdBZyMIiM=,tag:V6xE/t06FGb0JjImPeyylA==,type:str]
    pgp:
        - created_at: "2023-05-26T08:50:47Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA3bGu4MnJmFfAQ/8CE5A+L5rw/QIcKbhJf4/y+79vD0Q72Ed0795No2z0sV6
            2tDf9nX0jeb1UItRPAiAH/naxD2iW+bMr2F8lDeOSuVBxsJE5zklkCXZ1Mtl8IG/
            RmIPLdjAYyPvgmPOGba2sSRXl0q4YB6Xme51MUkVBGi/i9XzE3GBR+sFsPYPLtGI
            Ma5y31zeFWnxfeTiQkXpSQKbNPaLHOPwq5dZacwJxpPdQVJdyMeEbFgKCx7cTT7h
            3TiFsy9H5C4Sfx9VwttHmAtH0e5mfpjGz/BFU5knXBIOpOkgKI3BnSzq3l1PVMhX
            PXpP1eZkNIl2Mj5Rv1T3+iy5tr9XTpLxa7SiI9w8OIAYowbE6001uTZdjyyyTBte
            6ZZ+dlKaLW4sMhn0GnPNukv8dxn8twS98D73HM2IGOjtbsWOURUJgWow1vWUZo3k
            /moKHM3+OB7CYcXPAVrX9Y0HuRTferV8HlstNrST7lhNPHazk2gc5jitD8CSaf4t
            zvbWrHAWvgg713o7zhyb3GQAWYfd0x6JR5l5fqOkEETZwduIxuzLpSIlLmN/2j2Z
            IpdD6Vv1DSN4vWwr5lkt0X9iU+7imr51rdXq/zJI9C2rWXG3WlPP2zLm1YgxplD4
            LSCEuLmyPtwLcWtyADzvWEKrpTfddC2CadHHTSjC7JTZBvGcHTJtXaOaTUGbSMzS
            XgHOZ9qOTsCnfgIEyNUqjICu1baZNNKT0y1JyJzOPpt9waPdFUZ5YrXqD8ZUSXbf
            XMgLQeRhYtwADHDEtHiSQ7648uq/VJmsTZOMoQ9E1xzqpe66EtirQSNaacKqWyA=
            =Nv/Y
            -----END PGP MESSAGE-----
          fp: 171CF9C1D45CB28C5ECA2964FCC4AEC805651FBB
    encrypted_regex: ^(data|stringData|consumerKey|email|groupName|applicationKey|host|hosts|addresses|server|configLogicalBackup)$
    version: 3.7.3
