apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
    name: nfs-sc
    namespace: flux-system
spec:
    interval: 10m
    releaseName: nfs-sc
    chart:
        spec:
            chart: nfs-subdir-external-provisioner
            sourceRef:
                kind: HelmRepository
                name: kubernetes-sigs-nfs
                namespace: flux-system
            interval: 10m
    values:
        nfs:
            path: /DATA
            server: ENC[AES256_GCM,data:abbb1EmmGMKiSaU=,iv:uF4dZ5Y5XbQEPRU6h0EUM8g+wzfmLrgXkE6DLovm0og=,tag:mpxJ2Sw1j86kY+UJGJwANw==,type:str]
        storageClass:
            defaultClass: true
            name: nfs-sc
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-05-26T08:48:45Z"
    mac: ENC[AES256_GCM,data:X9zzJrPv+ZFOZZF/96uaC3n4pwwPJphyN1eeBXkzqz3NW07sNNQB7Wd3tBx/fovY3nzor0vQ6SYYX5soBofp3chotM/lv95gRBF+tN3Y+DzMFn+m86S3XI0lnNO0KJGiJVtiAWdnFBf5M7WZ2lQXMQXwnvEA9phgbgSXGKLw0+c=,iv:RyzEqdHrMV6hQFmSrsGyVMC1DOffQ2FA6roIjNitQds=,tag:bWdQug/8CqTWCurPG80a/A==,type:str]
    pgp:
        - created_at: "2023-05-26T08:48:45Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA3bGu4MnJmFfARAAySjIUft4zltMVyD2ED4lRnToy1Nh14mHqS/vru/qo/nw
            ZOvLKwBPsOV29vnxKQpT5g/IHOD6ntUtOS6PIut5noMpddP4je30EYiMauB9kb+2
            suBWlyUm2yPLCVbljEqwyTjLyV9cXQfbP9C9bA7Eg1I+9w5GCPdAtHPUfZwZkAtT
            jAvo8+2eVjXTXVYCmHoe1HzaQrt51Hq/q1rk3MfJXLYY8EgL27l9uSUxvkdcayHg
            fuRk82FlCrxwy1q/ax2uJJx8jq+DJGHm1ueeENsPjBT/8w24K9NLK7XVvDfKj1q5
            +dROtZeXBQIxCNdxDcx0RZtbJbRqk9P/yfVJOz1PRgsLFamHiQpRRcHAnDY08hVe
            o1qYECfbnrFoO6E3a375LpicTLt59llWl6lYVuapxNecU4Dj6zf5EX5WNX5anmWi
            fgafiYjo5CFh3DgCuujBRMV7a7XMIjdk5ENTBfEXSUH7xPYgZvxuVbbiW3MyERn+
            f45c4Ezip9vEFw4eHRFuFX+95FH3ghAKSKHjPhxvhfaHYcE/QLA8/ls6DpWF9c/N
            +gJqAdg+WEz8M/4eSd2qCaMN9F0GJz+rAjLw72+JrU6KTPP2WwpFn3s2xJ9Y7sqn
            +X1G+fuVlH6F34p2aWzD1/XdUBaeerB2+0/pBEMhrrtMvtGc1vsCb+NVY0s5qbXS
            XAGDaVtcuzfhNcB1NaWvGlRq68Aca+Ai+b/KWXbXbLflMJ5PGMlwVopqYPbMEk/W
            WF/q+vcFPmG5jZX1DfDxZ+vGQ6MIJzTh6U/O7NDpV7DXEETA1g4ksUNl81xM
            =S/YJ
            -----END PGP MESSAGE-----
          fp: 171CF9C1D45CB28C5ECA2964FCC4AEC805651FBB
    encrypted_regex: ^(data|stringData|consumerKey|email|groupName|applicationKey|host|hosts|addresses|server|configLogicalBackup)$
    version: 3.7.3
