apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nfs-sc
  namespace: flux-system
spec:
  interval: 10m
  releaseName: nfs-sc
  chart:
    spec:
      chart: nfs-subdir-external-provisioner
      sourceRef:
        kind: HelmRepository
        name: kubernetes-sigs-nfs
        namespace: flux-system
      interval: 10m
  values:
    nfs:
      path: /DATA/k8s/storage/gitops-nfs
      server: "10.12.12.80"
    storageClass:
      defaultClass: true
      name: nfs-sc
