apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
    name: first-pool
    namespace: metallb-system
spec:
    addresses:
        - ENC[AES256_GCM,data:iaAMkzYIT+mtSrllMNUQQGcyxsK3GINs0A==,iv:SC4TdffrzxidYUQfkPSLDKdujKOKEQu0/+YRXuXZZzU=,tag:gwTcDA9Mlu60z4Q0zlbKzQ==,type:str]
    autoAssign: true
    avoidBuggyIPs: false
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-05-07T21:56:12Z"
    mac: ENC[AES256_GCM,data:nhy8TZ59I2SoVPuVk31ppWHH2Y2DWyH+V+7fCSVngaQT2xVH7V/oKqAdWz1NoI8vyyxcYQH1+3XgYOCoOn6+ENlQ+l127TZL1/6u/tq+88JFpwEvsmhiM1MV+AK/e8ILMXaLA1d4jf9B04cppmYSj+PhOJTm6+8a4CWvC5x0V5s=,iv:d4w5xl7nv362pCv0h3w2vqD6qJJ7HqUyoYLkT/jdhJo=,tag:GF6VodgeihIIXOfsvVp/Fg==,type:str]
    pgp:
        - created_at: "2023-05-07T21:56:10Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA3bGu4MnJmFfARAAn6nmBkw1mwBo6s2HXEWl2yD3SXx9JluOg0+s9FQT9ios
            DfZnOekTz+8VbmTGHrO3F9jE5qsqhFuW0HaSk7fZxjkvTQ017Tigyph9AAhbkpe0
            Isoy84nCDyZtIlL7Su4CTDLkqZs3fsLSZ0iNIwrhf3Bye1KfYK+51+g4/3VwwCMg
            RvkM0/TYE6S4Z91ixlQCvj34vOZZl1ZvLrr5wzfjeyEV+6qsXB5CY/xwWbNf+74P
            LKuxnUPS8CjdvskyvUsoGSPs2VLktqivYTd6vVZKCXV13btiXVsk4E2tT5XZnRlD
            VV7WGKTULwqHZ9TSZo8hTaJbyqndX08MpL5tcySIrDdP6nKfDSV4AbkTuRTH4eOt
            vomqEYCbxLuOfnr5cjEKzosUe6Aj3UxIyW8PeS5ptvLJQiE8kMEPSIWC178OSkdG
            47HIEpUZ6t0jAEWzrjYvxBJ5q+3XvCFoF3AqKh7h+wKIbuh7B4p3V20a/DkZsXsB
            1e+xbAbkgXkhJ60oy/+bDaJQeTGfQ511EgoGHtkCb/W5eONfbUX/WMpPURji+T1b
            6ExOQVnARkwRHlz9SK9gL3go6SfNOjr+GQgtm7dAm9iIQb5QVQLfTOaIxHG9xfdy
            cvASJX6aJAZZ8e3Ce7zfrWAsWxuqzh4cG6WJx+F9rFQurdGQHC2n2UyA9WXGsSvS
            XAFkCm3gI9cxe5kHIKmv6OTblTX/Xha3js2Bso6xUGwIhQdV1p7HxlgwMZRv6Zrn
            iEn5KT5kdB0zPcLYZABq09G2CLtD6k6wc0gkP2nnSXovhZBMgE6QYenl2QCB
            =DCh2
            -----END PGP MESSAGE-----
          fp: 171CF9C1D45CB28C5ECA2964FCC4AEC805651FBB
    encrypted_regex: ^(data|stringData|consumerKey|email|groupName|applicationKey|host|hosts|addresses|server|configLogicalBackup)$
    version: 3.7.3
