apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../apps/monicahq/
patches:
  - path: helmrelease.yaml
configMapGenerator:
  - name: monicahq-values
    namespace: flux-system
    files:
      - values.yaml=values.yaml
secretGenerator:
  - name: monicahq-secrets
    namespace: flux-system
    files:
      - values.yaml=secrets.yaml
configurations:
  - kustomizeconfig.yaml
