apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: flux-system
  labels:
    org.zroot.gitops: infra
spec:
  interval: 10m
  releaseName: cert-manager
  targetNamespace: cert-manager
  chart:
    spec:
      chart: cert-manager
      version: ">=1.11.0"
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: flux-system
      interval: 10m
  install:
    createNamespace: true
    replace: true
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    installCRDs: true
    resources:
      requests:
        cpu: 200m
        memory: 128Mi
    prometheus:
      enabled: true
      servicemonitor:
        enabled: false #to be enabled after promethues, this is a strict dependency
