apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: certs
  namespace: flux-system
  labels:
    org.zroot.gitops: infra
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./high/infra/certs/overlays/astrid
  prune: true
  dependsOn:
    - name: cert-manager
      namespace: flux-system