apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: traccar
  namespace: flux-system
spec:
  interval: 10m0s
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./high/overlays/astrid/traccar
  prune: true
  dependsOn:
    - name: cert-manager
      namespace: flux-system
    - name: certs
      namespace: flux-system