apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: monicahq
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/monicahq/helm
  ref:
    tag: monica-1.0.6
  ignore: |
    # exclude all
    /*
    # include charts directory
    !/charts/
