---
- name: "Prepare pixie server"
  hosts: pixie
  gather_facts: true
  become: true
  tasks:
    - name: "Install go language"
      ansible.builtin.package:
        name: go
        state: latest
    - name: "Install pixiecore"
      ansible.builtin.shell: go install go.universe.tf/netboot/cmd/pixiecore@latest
    - name: "Move pixiecore to /usr/bin"
      ansible.builtin.copy:
        remote_src: true
        src: /root/go/bin/pixiecore
        dest: /usr/bin/pixiecore
        mode: a+x

    - name: "Install pixiecore systemd unit"
      ansible.builtin.copy:
        src: ../templates/pixiecore.systemd.tpl
        dest: /etc/systemd/system/pixiecore.service
        mode: 0664

    - name: "Download Talos Linux kernel image"
      ansible.builtin.get_url:
        url: https://github.com/siderolabs/talos/releases/download/v1.0.1/vmlinuz-amd64
        dest: /root/vmlinuz-amd64
        checksum: sha256:427037dbf2b48be30140ebe5ceb86e1f3d233756e33fc0a67d3851aa772c91fa

    - name: "Download Talos Linux initrd"
      ansible.builtin.get_url:
        url: https://github.com/siderolabs/talos/releases/download/v1.0.1/initramfs-amd64.xz
        dest: /root/initramfs-amd64.xz
        checksum: sha256:2844dd9831315f6d2106c019d17b3734f89c706d63624cb6909b60e8a662f276

    - name: "Start pixiecore service"
      ansible.builtin.systemd:
        name: pixiecore
        state: started
        daemon_reload: yes
        enabled: yes