name: check

on:
  pull_request:
  push:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - uses: actions/setup-python@v2

    - name: Setup terraform
      uses: hashicorp/setup-terraform@v1.3.2
      with:
         terraform_version: 1.1.8

    - name: Setup terraform docs
      uses: draios/action-setup-terraform-docs@v0.0.2

    - name: Install arkade
      if:  ${{ ! ((github.event_name == 'push') && (github.ref == 'refs/heads/main')) }}
      uses: alexellis/setup-arkade@v3
    - uses: alexellis/arkade-get@master
      if:  ${{ ! ((github.event_name == 'push') && (github.ref == 'refs/heads/main')) }}
      with:
        kubectl: latest
        helm: latest
        kubeconform: latest
        kustomize: latest
    - uses: pre-commit/action@v2.0.3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Check flux resources
      shell: bash
      run: .github/workflows/check.sh