apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../apps/traccar/
  - ./traefikmiddleware.yaml
patches:
  - path: helmrelease.yaml
configMapGenerator:
  - name: traccar-values
    namespace: flux-system
    files:
      - values.yaml=values.yaml
secretGenerator:
  - name: traccar-secrets
    namespace: flux-system
    files:
      - values.yaml=secrets.yaml
configurations:
  - kustomizeconfig.yaml
